cloud:
  gateway:
    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins: http://localhost:4200
          allowCredentials: true
          allowedHeaders:
            - content-type
            - token
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS